### ISSUE TITLE
자가진단 항목 변경

### ISSUE THREAD

**Issue by minikupa** [comjun04/covid19-hcheck-auto#7]
최근 자가진단 항목이 변경되어 자가진단이 안되는 것  같네요.

**Comment by minikupa** [comment]
계속 이름, 생일이 잘못됐다 뜨네요

**Comment by lhwdev** [comment]
혹시 학년이 올라가서 안 되는건 아닐까요? 자가진단 공식 사이트에 들어가서 로그인해보세요.

**Comment by minikupa** [comment]
공식 사이트에서 새로 변경된 정보로 가입했습니다. 공식 홈페이지에서는 잘 되지만, 이걸 사용하면 저 문구가 뜨네요.

**Comment by comjun04** [comment]
늦게 확인해서 죄송합니다.
신학기로 인해 학교에서 정보가 변경되어 다시 가입해야 제대로 작동합니다.
사이트에서 학생정보로 다시 가입하면 잘 작동할 겁니다.

혹시 그 이후에도 문제 생기면 이슈 남겨주세요
