### ISSUE TITLE
학생 정보 찾기 오류

### ISSUE THREAD

**Issue by minikupa** [comjun04/covid19-hcheck-auto#8]
api.finduser 부근에서 오류가 납니다. 제가 오류 내용을 잘못봤어네요.. 제가 좀 멀리 나와있는 상태인데, 제작자님은 문제 없이 되시나요?

**Comment by minikupa** [comment]
아직 이유는 찾지 못했지만, 서버를 재부팅하니 해결됐네요..

**Comment by comjun04** [comment]
> api.finduser 부근에서 오류가 납니다. 제가 오류 내용을 잘못봤어네요.. 제가 좀 멀리 나와있는 상태인데, 제작자님은 문제 없이 되시나요?

@minikupa 
일주일이나 확인 못해서 죄송합니다.

혹시 그때 뜬 오류가 무엇인지 알 수 있을까요?
